server:
  port: 8001
eureka:
  client:                                                   #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://admin:123456@localhost:5678/eureka/

      #集群是
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: microservicecloud-dept8001
#    prefer-ip-address: true                                  #访问路径可以显示IP地址

#服务的名称
spring:
  application:
    name: providerOne
